### ISSUE TITLE
xar 1.5.2 does not build on Mac OS X 10.5.5 (Xcode 3.1.1)

### ISSUE THREAD

**Issue by GoogleCodeExporter** [jevinskie/xar#63]
```
What steps will reproduce the problem?

1. Just try to build it it

What is the expected output? 

Successful build is expected.

What do you see instead?

Undefined symbols:
  "_xmlDictCleanup", referenced from:
      _xar_unserialize in archive.o
      _xar_unserialize in archive.o
      _xar_unserialize in archive.o
      _xar_unserialize in archive.o
      _xar_unserialize in archive.o
ld: symbol(s) not found

What version of the product are you using? 

1.5.2.

On what operating system?

Mac OS X 10.5.5. Xcode 3.1.1

```

Original issue reported on code.google.com by `grosjamb...@gmail.com` on 7 Dec 2008 at 11:14
